### ISSUE TITLE
Label overflow on checkbox 

### ISSUE THREAD

**Issue by LastCodeDE** [syncfusion/ej2-ng-buttons#5]
Hello,

we are using ej-checkbox on our project.

Unfortunately if we are setting a long label on the component the label is overflowing the checkbox.
(See attachment)

![checkbox](https://user-images.githubusercontent.com/15675686/35049568-b69d0652-fba0-11e7-8e66-66ba042679cd.PNG)

Additional I added the plunker project too.
[checkbox.zip](https://github.com/syncfusion/ej2-ng-buttons/files/1639463/checkbox.zip)

Regards

**Comment by Shanmugarajakaliappan** [comment]
Hi @LastCodeDE ,

We can able to reproduce the issue in our end so, we have logged a defect report “**Wrapped text overlaps frame icon in Checkbox**” for the same and the fix will be available in our January 30, 2018 release. We will update you once the fix for the issue is available until then we appreciate your patience. 
 
Regards, 
Shanmugaraja K

**Comment by Shanmugarajakaliappan** [comment]
Hi @LastCodeDE ,

We are glad to announce that patch release ([v 15.4.27](https://www.npmjs.com/package/@syncfusion/ej2-buttons)) is rolled out successfully and in that release, we have added the fix for “**Wrapped text overlaps frame icon in Checkbox**” issue.   

Regards,
Shanmugaraja K

**Comment by LastCodeDE** [comment]
HI @Shanmugarajakaliappa,

with v 15.4.27  the failure is not existing anymore.

Unfortunately now wrapping doesn't work anymore.I think the reason is the fix.
It lost his responsiveness.

I would ask you to check this

**Comment by silambarasani** [comment]
Hi @LastCodeDE ,

We would like to let you know that as per our current implementation behavior, CheckBox label with wrapped text doesn’t get applied by default.  So, we suggest you to override this behavior by using ‘**_[cssClass](http://ej2.syncfusion.com/15.4.23/documentation/check-box/api-checkBox.html?lang=typescript#cssclass)_**’ property in CheckBox. Please refer the below sample.

[Plunker Sample](http://plnkr.co/edit/mWXvrUgQ0ihKx6dhDf9M?p=preview)

**_html_**
```
.e-customcss-wrap .e-label {
    white-space: normal;
}
```
Thanks,
Silambarasan Ilango

**Comment by Shanmugarajakaliappan** [comment]
Hi @LastCodeDE ,

We are glad to announce that patch release ([v 15.4.30](https://www.npmjs.com/package/@syncfusion/ej2-buttons)) is rolled out successfully and in that release, we have added the fix for the checkbox label responsive issue.

Regards,
Shanmugaraja K
